# Generated by Django 4.2.1 on 2023-05-24 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualdata',
            old_name='well',
            new_name='API_WELL_NUMBER',
        ),
        migrations.RenameField(
            model_name='annualdata',
            old_name='brine',
            new_name='BRINE',
        ),
        migrations.RenameField(
            model_name='annualdata',
            old_name='gas',
            new_name='GAS',
        ),
        migrations.RenameField(
            model_name='annualdata',
            old_name='oil',
            new_name='OIL',
        ),
    ]
